name: .NET 7 + Pack + Push no NuGet

on:
  push:
    branches: [ main ]

jobs:
  pack-push:
    env:
      CAMINHO_SOLUCAO: ./src/SimpleJobs/SimpleJobs.sln
      CAMINHO_PROJETO: ./src/SimpleJobs/SimpleJobs/SimpleJobs.csproj
      CAMINHO_PROJETO_TESTE: ./src/SimpleJobs/SimpleJobs.Test/SimpleJobs.Test.csproj

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: 7.0.101

    - name: Restore Defaults
      run: dotnet restore ${{ env.CAMINHO_SOLUCAO }}

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out
      
    - name: Teste do package
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTE }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        PACKAGE=$(find -iname \SimpleJobs*.nupkg* -type f | head -1)
        dotnet nuget push ${PACKAGE} --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate

