name: .NET 7 + Pack + Push no NuGet

on:
  push:
    branches: [ main ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./src/SimpleJobs/SimpleJobs/SimpleJobs.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.101

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push SimpleJobs.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate

